limit-num:
  # 功能开关：是否限制物品附魔类型数量
  slimefun-enable: true
  # 粘液科技自动附魔机最大附魔种类数量
  slimefun-enchanter-max-num: 5
  # 功能开关：是否限制原版附魔
  limit-vanilla: true
  # 最大附魔种类数量
  vanilla-max-num: 5

message:
  vanilla-num-limit-reached: "无法附魔 该物品的附魔种类已达上限 %max% 个"
  slimefun-num-limit-reached: "无法附魔 该物品的附魔种类已达上限 %max% 个"