name: SfEnchanterLimit
version: '${project.version}'
author: Jin_ou
main: me.jinou.sfenchanterlimit.SfEnchanterLimit
api-version: 1.18
depend:
  - Slimefun
commands:
  sfenchanterlimit:
    aliases: sel